# Generated by Django 4.2.7 on 2023-11-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencia',
            name='id',
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='id_emergencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
