# Generated by Django 4.2.7 on 2023-11-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_emergencia_id_alter_emergencia_id_emergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencia',
            name='tipo_emergencia',
        ),
    ]
